name: Tests

on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test

    strategy:
      matrix:
        node-version: [12.x, 14.X, 16.x, 17.X]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install globally grunt-cli
        run: npm install -g grunt-cli

      - name: Install other dependencies
        run: npm install

      - name: Run tests (QA and unit tests)
        run: npm test

      - name: SonarCloud Scan
        if: (matrix.node-version == '16.x') && (github.event_name != 'pull_request')
        uses: sonarsource/sonarcloud-github-action@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/v')
    name: Release on GitHub and NPM

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install globally grunt-cli
        run: npm install -g grunt-cli

      - name: Install other dependencies
        run: npm install

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false

      - name: Create NPM release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
